export const univList = {
    "한양대학교 에리카": "@hanyang.ac.kr",
    "한양대학교": "@hanyang.ac.kr",
    "서울대학교": "@snu.ac.kr",
    "고려대학교": "@korea.co.kr",
    "연세대학교": "@yonsei.ac.kr",
    "서강대학교": "@sogang.ac.kr",
    "중앙대학교": "@cau.ac.kr",
    "경희대학교": "@khu.ac.kr",
    "한국외국어대학교":	"@hufs.ac.kr",
    "서울시립대학교": "@uos.ac.kr",
    "건국대학교": "@konkuk.ac.kr",
    "동국대학교": "@dongguk.edu",
    "홍익대학교": "@hongik.ac.kr",
    "국민대학교": "@kookmin.ac.kr",
    "숭실대학교": "@soongsil.ac.kr",
    "세종대학교": "@sju.ac.kr",
    "단국대학교": "@dankook.ac.kr",
    "광운대학교": "@kw.ac.kr",
    "명지대학교(인문캠)": "@mju.ac.kr",
    "명지대학교(자연캠)": "@mju.ac.kr",
    "상명대학교": "@smu.ac.kr",
    "경기대학교": "@kyonggi.ac.kr",
    "가톨릭대학교":	"@catholic.ac.kr",
    "삼육대학교": "@syuac.kr",
    "서울여자대학교": "@swu.ac.kr",
    "성신여자대학교": "@sungshin.ac.kr",
    "이화여자대학교": "@ehwa.ac.kr",
    "부산대학교": "@pusan.ac.kr",
    "경북대학교": "@knu.ac.kr",
    "충남대학교": "@cnu.ac.kr",
    "충북대학교": "@chungbuk.ac.kr",
    "전남대학교": "@jnu.ac.kr",
    "전북대학교": "@jbnu.ac.kr",
    "인하대학교": "@inha.ac.kr",
    "아주대학교": "@ajou.ac.kr"
}